---
- hosts: localhost

  tasks:
  - name: password reject
    lineinfile:
      path: /etc/pam.d/common-password
      regexp: '^password\s*requisite\s*pam_cracklib.so'
      line: 'password        requisite                       pam_cracklib.so retry=3 minlen=8 difok=3 reject_username enforce_for_root'
