---
- name: Simple comand
  hosts: all
  become: yes

  tasks:

  - name: Create new file
    file:
     path: "/etc/iaac"
     state: touch
     mode: 0500

- name: Linux distro name & version
  hosts: all
  become: false

  tasks:

  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
